//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_login_regist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int Id { get; set; }
        public string content { get; set; }
        public string property_id { get; set; }
        public string customer_id { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
