//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_login_regist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_desc
    {
        public string Property1 { get; set; }
        public string property_detail { get; set; }
        public string property_state { get; set; }
        public string property_city { get; set; }
        public string property_street { get; set; }
        public string property_type { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
