//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Ass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string startDate { get; set; }
        public double price { get; set; }
        public string endDate { get; set; }
        public string comment { get; set; }
        public string AspNetUsersId { get; set; }
        public int PropertyId { get; set; }
        public int AgencyId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Property Property { get; set; }
        public virtual Agency Agency { get; set; }
    }
}
